version: "3.9"

services:
  content-service:
    build: ./content-service
    container_name: content-service
    ports:
      - "4000:4000"

  edge-cache:
    build: ./edge-cache
    container_name: edge-cache
    ports:
      - "3000:3000"
    depends_on:
      - content-service

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./monitoring/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
